package com.nira.niramart.config;

import javax.servlet.ServletContextEvent;
import javax.servlet.ServletContextListener;
import javax.servlet.annotation.WebListener;

import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;

@WebListener
public class DatabaseContextListener implements ServletContextListener {

    @Override
    public void contextInitialized(ServletContextEvent sce) {

        String sql = """
                CREATE TABLE IF NOT EXISTS users (
                    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    name VARCHAR(100) NOT NULL,
                    email VARCHAR(150) NOT NULL UNIQUE,
                    password VARCHAR(255) NOT NULL,
                    role VARCHAR(30) NOT NULL
                )
                """;

        try (
                Connection connection =
                        DatabaseConfig.getDataSource().getConnection();

                Statement statement =
                        connection.createStatement()
        ) {

            statement.executeUpdate(sql);

            System.out.println("H2 database initialized successfully.");

        } catch (SQLException e) {

            throw new RuntimeException(
                    "Database initialization failed",
                    e
            );
        }
    }

    @Override
    public void contextDestroyed(ServletContextEvent sce) {

        if (DatabaseConfig.getDataSource() != null) {
            DatabaseConfig.getDataSource().close();
            System.out.println("HikariCP connection pool closed.");
        }
    }
}